services:
  api:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: que-backend
    restart: always
    env_file: server/.env
    volumes:
      - ${BE_LOG_HOST_PATH}:${BE_LOG_CONTAINER_PATH}
    ports:
      - "3000:3000"
    networks:
      - que-network

networks:
  que-network:
    external: true