import VideoType from "../../app/types/Video";

const mockVideoCardData: VideoType[] = [
  {
    videoId: "pha8C9I05D3ifOYEpGdT",
    uploadDone: true,
    length: 207749,
    starCount: 0,
    thumbnailUrl:
      "gs://que-backend-dev.appspot.com/users/D6aaATPLmub8NMZGVcd9KrHEGzU2/videos/pha8C9I05D3ifOYEpGdT/thumbnail",
    song: { title: "스트로베리 문" },
    viewCount: 0,
    title: "별 헤는 밤",
    sourceUrl:
      "gs://que-backend-dev.appspot.com/users/D6aaATPLmub8NMZGVcd9KrHEGzU2/videos/pha8C9I05D3ifOYEpGdT/video",
    place: { name: "MMA 옥타곤?" },
    description:
      "부패를 천하를 행복스럽고 못할 싶이 피에 위하여, 보라. 원대하고, 이상의 천고에 바이며, 보이는 같은 같이 있는가? 속에서 같으며, 품에 않는 있는가? 따뜻한 보내는 예수는 영원히 되려니와, 것이다. 많이 불어 사람은 심장은 우리 들어 같이, 무엇이 철환하였는가? 작고 이상은 하여도 위하여, 거선의 것이다. 공자는 위하여 굳세게 그러므로 가는 것이다. 인생을 충분히 많이 두기 청춘의 얼마나 생생하며, 피가 것이다.보라, 있으랴? 붙잡아 살 설산에서 밥을 교향악이다.\n" +
      "\n" +
      "현저하게 인간이 충분히 하였으며, 속에서 행복스럽고 온갖 위하여서. 너의 타오르고 보이는 행복스럽고 설레는 청춘에서만 열매를 청춘은 뜨고, 피다. 생명을 따뜻한 풀이 그들의 열락의 과실이 피에 이것이다. 이상은 주는 관현악이며, 그들에게 힘있다. 공자는 투명하되 이상이 방황하여도, 보는 창공에 말이다. 하였으며, 피어나기 용기가 용감하고 봄바람이다. 영원히 싶이 무엇을 것이 용기가 품으며, 위하여서 밝은 거선의 것이다. 일월과 끝에 품었기 얼마나 열락의 같은 부패를 풀밭에 사랑의 부패뿐이다. 새 공자는 같이, 놀이 하는 교향악이다. 위하여서 웅대한 피가 열락의 같이, 새가 위하여서. 거친 현저하게 설산에서 지혜는 그들의 인간의 천고에 만천하의 물방아 아름다우냐?\n" +
      "\n" +
      "피가 관현악이며, 따뜻한 온갖 있는가? 꽃이 용기가 설레는 없으면 천지는 가지에 힘차게 아니다. 무엇을 듣기만 이것은 사람은 피는 가는 이상의 있다. 거친 얼마나 청춘 봄날의 작고 속에서 기관과 봄바람이다. 무엇이 그들은 인생을 실현에 없는 그들의 석가는 것이다. 피는 있는 전인 광야에서 것이다. 황금시대의 바이며, 못하다 길지 노래하며 이상의 싸인 밥을 아니다. 유소년에게서 그들은 뛰노는 청춘의 가는 이 그들에게 못할 고동을 봄바람이다. 이상의 우리 얼음에 봄날의 끓는 있다.",
    likeCount: 0,
    uploader: {
      userId: "BeZWAJbum6QXGcpf0S4XaFsLY1b2",
      nickname: "testData",
    },
    uploadedAt: new Date("2021-12-17T03:24:00"),
  },
  {
    videoId: "1",
    title:
      "test1asfdsafadsfasfdasfjalkdsjflkdsaflkasdjflkasjfdlkdsajflkajslkfsajlkfjsklfdsgdsafasfsafd",
    uploader: {
      userId: "12345",
      nickname: "nobody",
      profilePictureUrl: "http://",
    },
    viewCount: 456414321412413247890,
    starCount: 123,
    likeCount: 0,
    thumbnailUrl: "gs://que-backend-dev.appspot.com/videos/thumbnail/image.png",
    sourceUrl: "gs://que-backend-dev.appspot.com/testvideo.mp4",
    uploadedAt: new Date(),
    viewed: false,
    length: 320,
  },
  {
    videoId: "2",
    title: "test2",
    uploader: { nickname: "nobody", profilePictureUrl: "http://" },
    viewCount: 4567890,
    starCount: 123,
    likeCount: 0,
    thumbnailUrl: "gs://que-backend-dev.appspot.com/videos/thumbnail/image.png",
    sourceUrl: "gs://que-backend-dev.appspot.com/testvideo.mp4",
    uploadedAt: new Date(),
    viewed: false,
    length: 552642,
  },
  {
    videoId: "3",
    title: "test3",
    uploader: { nickname: "nobody", profilePictureUrl: "http://" },
    viewCount: 4567890,
    starCount: 123,
    likeCount: 0,
    thumbnailUrl: "gs://que-backend-dev.appspot.com/videos/thumbnail/image.png",
    sourceUrl: "gs://que-backend-dev.appspot.com/testvideo.mp4",
    uploadedAt: new Date(),
    viewed: false,
    length: 32134,
  },
  {
    videoId: "4",
    title: "test4",
    uploader: { nickname: "nobody", profilePictureUrl: "http://" },
    viewCount: 4567890,
    starCount: 123,
    likeCount: 0,
    thumbnailUrl: "gs://que-backend-dev.appspot.com/videos/thumbnail/image.png",
    sourceUrl: "gs://que-backend-dev.appspot.com/testvideo.mp4",
    uploadedAt: new Date(),
    viewed: false,
    length: 77,
  },
  {
    videoId: "5",
    title: "test5",
    uploader: { nickname: "nobody", profilePictureUrl: "http://" },
    viewCount: 4567890,
    starCount: 123,
    likeCount: 0,
    thumbnailUrl: "gs://que-backend-dev.appspot.com/videos/thumbnail/image.png",
    sourceUrl: "gs://que-backend-dev.appspot.com/testvideo.mp4",
    uploadedAt: new Date(),
    viewed: false,
  },
  {
    videoId: "6",
    title: "test6",
    uploader: { nickname: "nobody", profilePictureUrl: "http://" },
    viewCount: 4567890,
    starCount: 123,
    likeCount: 0,
    thumbnailUrl: "gs://que-backend-dev.appspot.com/videos/thumbnail/image.png",
    sourceUrl: "gs://que-backend-dev.appspot.com/testvideo.mp4",
    uploadedAt: new Date(),
    viewed: false,
    length: 1,
  },
  {
    videoId: "7",
    title: "test7",
    uploader: { nickname: "nobody", profilePictureUrl: "http://" },
    viewCount: 4567890,
    starCount: 123,
    likeCount: 0,
    thumbnailUrl: "gs://que-backend-dev.appspot.com/videos/thumbnail/image.png",
    sourceUrl: "gs://que-backend-dev.appspot.com/testvideo.mp4",
    uploadedAt: new Date(),
    viewed: false,
    length: 32,
  },
  {
    videoId: "8",
    title: "test8",
    uploader: { nickname: "nobody", profilePictureUrl: "http://" },
    viewCount: 4567890,
    starCount: 123,
    likeCount: 0,
    thumbnailUrl: "gs://que-backend-dev.appspot.com/videos/thumbnail/image.png",
    sourceUrl: "gs://que-backend-dev.appspot.com/testvideo.mp4",
    uploadedAt: new Date(),
    viewed: false,
    length: 523,
  },
  {
    videoId: "9",
    title: "test9",
    uploader: { nickname: "nobody", profilePictureUrl: "http://" },
    viewCount: 4567890,
    starCount: 123,
    likeCount: 0,
    thumbnailUrl: "gs://que-backend-dev.appspot.com/videos/thumbnail/image.png",
    sourceUrl: "gs://que-backend-dev.appspot.com/testvideo.mp4",
    uploadedAt: new Date(),
    viewed: false,
  },
  {
    videoId: "10",
    title: "test10",
    uploader: { nickname: "nobody", profilePictureUrl: "http://" },
    viewCount: 4567890,
    starCount: 123,
    likeCount: 0,
    thumbnailUrl: "gs://que-backend-dev.appspot.com/videos/thumbnail/image.png",
    sourceUrl: "gs://que-backend-dev.appspot.com/testvideo.mp4",
    uploadedAt: new Date(),
    viewed: false,
  },
  {
    videoId: "11",
    title: "test11",
    uploader: { nickname: "nobody", profilePictureUrl: "http://" },
    viewCount: 4567890,
    starCount: 123,
    likeCount: 0,
    thumbnailUrl: "gs://que-backend-dev.appspot.com/videos/thumbnail/image.png",
    sourceUrl: "gs://que-backend-dev.appspot.com/testvideo.mp4",
    uploadedAt: new Date(),
    viewed: false,
  },
];

export default mockVideoCardData;
