/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IntroRouteImport } from './routes/intro'
import { Route as StackedLayoutRouteImport } from './routes/_stackedLayout'
import { Route as LandingLayoutRouteImport } from './routes/_landingLayout'
import { Route as AppLayoutRouteImport } from './routes/_appLayout'
import { Route as AppLayoutIndexRouteImport } from './routes/_appLayout/index'
import { Route as StackedLayoutUploadRouteImport } from './routes/_stackedLayout/upload'
import { Route as LandingLayoutSignupRouteImport } from './routes/_landingLayout/signup'
import { Route as LandingLayoutLoginRouteImport } from './routes/_landingLayout/login'
import { Route as AppLayoutSettingRouteImport } from './routes/_appLayout/setting'
import { Route as AppLayoutSearchRouteImport } from './routes/_appLayout/search'
import { Route as AppLayoutAlertRouteImport } from './routes/_appLayout/alert'
import { Route as AppLayoutStudioLayoutRouteImport } from './routes/_appLayout/_studioLayout'
import { Route as AppLayoutStageStageIdRouteImport } from './routes/_appLayout/stage/$stageId'
import { Route as AppLayoutStudioLayoutStudioHandleIndexRouteImport } from './routes/_appLayout/_studioLayout/studio/$handle/index'
import { Route as AppLayoutStudioLayoutStudioHandleStagesRouteImport } from './routes/_appLayout/_studioLayout/studio/$handle/stages'
import { Route as AppLayoutStudioLayoutStudioHandleReactionsRouteImport } from './routes/_appLayout/_studioLayout/studio/$handle/reactions'
import { Route as AppLayoutStudioLayoutStudioHandleBoardRouteImport } from './routes/_appLayout/_studioLayout/studio/$handle/board'

const IntroRoute = IntroRouteImport.update({
  id: '/intro',
  path: '/intro',
  getParentRoute: () => rootRouteImport,
} as any)
const StackedLayoutRoute = StackedLayoutRouteImport.update({
  id: '/_stackedLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingLayoutRoute = LandingLayoutRouteImport.update({
  id: '/_landingLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/_appLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutIndexRoute = AppLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const StackedLayoutUploadRoute = StackedLayoutUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => StackedLayoutRoute,
} as any)
const LandingLayoutSignupRoute = LandingLayoutSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => LandingLayoutRoute,
} as any)
const LandingLayoutLoginRoute = LandingLayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LandingLayoutRoute,
} as any)
const AppLayoutSettingRoute = AppLayoutSettingRouteImport.update({
  id: '/setting',
  path: '/setting',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutSearchRoute = AppLayoutSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutAlertRoute = AppLayoutAlertRouteImport.update({
  id: '/alert',
  path: '/alert',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutStudioLayoutRoute = AppLayoutStudioLayoutRouteImport.update({
  id: '/_studioLayout',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutStageStageIdRoute = AppLayoutStageStageIdRouteImport.update({
  id: '/stage/$stageId',
  path: '/stage/$stageId',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutStudioLayoutStudioHandleIndexRoute =
  AppLayoutStudioLayoutStudioHandleIndexRouteImport.update({
    id: '/studio/$handle/',
    path: '/studio/$handle/',
    getParentRoute: () => AppLayoutStudioLayoutRoute,
  } as any)
const AppLayoutStudioLayoutStudioHandleStagesRoute =
  AppLayoutStudioLayoutStudioHandleStagesRouteImport.update({
    id: '/studio/$handle/stages',
    path: '/studio/$handle/stages',
    getParentRoute: () => AppLayoutStudioLayoutRoute,
  } as any)
const AppLayoutStudioLayoutStudioHandleReactionsRoute =
  AppLayoutStudioLayoutStudioHandleReactionsRouteImport.update({
    id: '/studio/$handle/reactions',
    path: '/studio/$handle/reactions',
    getParentRoute: () => AppLayoutStudioLayoutRoute,
  } as any)
const AppLayoutStudioLayoutStudioHandleBoardRoute =
  AppLayoutStudioLayoutStudioHandleBoardRouteImport.update({
    id: '/studio/$handle/board',
    path: '/studio/$handle/board',
    getParentRoute: () => AppLayoutStudioLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/intro': typeof IntroRoute
  '/alert': typeof AppLayoutAlertRoute
  '/search': typeof AppLayoutSearchRoute
  '/setting': typeof AppLayoutSettingRoute
  '/login': typeof LandingLayoutLoginRoute
  '/signup': typeof LandingLayoutSignupRoute
  '/upload': typeof StackedLayoutUploadRoute
  '/': typeof AppLayoutIndexRoute
  '/stage/$stageId': typeof AppLayoutStageStageIdRoute
  '/studio/$handle/board': typeof AppLayoutStudioLayoutStudioHandleBoardRoute
  '/studio/$handle/reactions': typeof AppLayoutStudioLayoutStudioHandleReactionsRoute
  '/studio/$handle/stages': typeof AppLayoutStudioLayoutStudioHandleStagesRoute
  '/studio/$handle': typeof AppLayoutStudioLayoutStudioHandleIndexRoute
}
export interface FileRoutesByTo {
  '/intro': typeof IntroRoute
  '/alert': typeof AppLayoutAlertRoute
  '/search': typeof AppLayoutSearchRoute
  '/setting': typeof AppLayoutSettingRoute
  '/login': typeof LandingLayoutLoginRoute
  '/signup': typeof LandingLayoutSignupRoute
  '/upload': typeof StackedLayoutUploadRoute
  '/': typeof AppLayoutIndexRoute
  '/stage/$stageId': typeof AppLayoutStageStageIdRoute
  '/studio/$handle/board': typeof AppLayoutStudioLayoutStudioHandleBoardRoute
  '/studio/$handle/reactions': typeof AppLayoutStudioLayoutStudioHandleReactionsRoute
  '/studio/$handle/stages': typeof AppLayoutStudioLayoutStudioHandleStagesRoute
  '/studio/$handle': typeof AppLayoutStudioLayoutStudioHandleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_appLayout': typeof AppLayoutRouteWithChildren
  '/_landingLayout': typeof LandingLayoutRouteWithChildren
  '/_stackedLayout': typeof StackedLayoutRouteWithChildren
  '/intro': typeof IntroRoute
  '/_appLayout/_studioLayout': typeof AppLayoutStudioLayoutRouteWithChildren
  '/_appLayout/alert': typeof AppLayoutAlertRoute
  '/_appLayout/search': typeof AppLayoutSearchRoute
  '/_appLayout/setting': typeof AppLayoutSettingRoute
  '/_landingLayout/login': typeof LandingLayoutLoginRoute
  '/_landingLayout/signup': typeof LandingLayoutSignupRoute
  '/_stackedLayout/upload': typeof StackedLayoutUploadRoute
  '/_appLayout/': typeof AppLayoutIndexRoute
  '/_appLayout/stage/$stageId': typeof AppLayoutStageStageIdRoute
  '/_appLayout/_studioLayout/studio/$handle/board': typeof AppLayoutStudioLayoutStudioHandleBoardRoute
  '/_appLayout/_studioLayout/studio/$handle/reactions': typeof AppLayoutStudioLayoutStudioHandleReactionsRoute
  '/_appLayout/_studioLayout/studio/$handle/stages': typeof AppLayoutStudioLayoutStudioHandleStagesRoute
  '/_appLayout/_studioLayout/studio/$handle/': typeof AppLayoutStudioLayoutStudioHandleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/intro'
    | '/alert'
    | '/search'
    | '/setting'
    | '/login'
    | '/signup'
    | '/upload'
    | '/'
    | '/stage/$stageId'
    | '/studio/$handle/board'
    | '/studio/$handle/reactions'
    | '/studio/$handle/stages'
    | '/studio/$handle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/intro'
    | '/alert'
    | '/search'
    | '/setting'
    | '/login'
    | '/signup'
    | '/upload'
    | '/'
    | '/stage/$stageId'
    | '/studio/$handle/board'
    | '/studio/$handle/reactions'
    | '/studio/$handle/stages'
    | '/studio/$handle'
  id:
    | '__root__'
    | '/_appLayout'
    | '/_landingLayout'
    | '/_stackedLayout'
    | '/intro'
    | '/_appLayout/_studioLayout'
    | '/_appLayout/alert'
    | '/_appLayout/search'
    | '/_appLayout/setting'
    | '/_landingLayout/login'
    | '/_landingLayout/signup'
    | '/_stackedLayout/upload'
    | '/_appLayout/'
    | '/_appLayout/stage/$stageId'
    | '/_appLayout/_studioLayout/studio/$handle/board'
    | '/_appLayout/_studioLayout/studio/$handle/reactions'
    | '/_appLayout/_studioLayout/studio/$handle/stages'
    | '/_appLayout/_studioLayout/studio/$handle/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
  LandingLayoutRoute: typeof LandingLayoutRouteWithChildren
  StackedLayoutRoute: typeof StackedLayoutRouteWithChildren
  IntroRoute: typeof IntroRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/intro': {
      id: '/intro'
      path: '/intro'
      fullPath: '/intro'
      preLoaderRoute: typeof IntroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_stackedLayout': {
      id: '/_stackedLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof StackedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landingLayout': {
      id: '/_landingLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LandingLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_appLayout': {
      id: '/_appLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_appLayout/': {
      id: '/_appLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppLayoutIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_stackedLayout/upload': {
      id: '/_stackedLayout/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof StackedLayoutUploadRouteImport
      parentRoute: typeof StackedLayoutRoute
    }
    '/_landingLayout/signup': {
      id: '/_landingLayout/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof LandingLayoutSignupRouteImport
      parentRoute: typeof LandingLayoutRoute
    }
    '/_landingLayout/login': {
      id: '/_landingLayout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LandingLayoutLoginRouteImport
      parentRoute: typeof LandingLayoutRoute
    }
    '/_appLayout/setting': {
      id: '/_appLayout/setting'
      path: '/setting'
      fullPath: '/setting'
      preLoaderRoute: typeof AppLayoutSettingRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_appLayout/search': {
      id: '/_appLayout/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppLayoutSearchRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_appLayout/alert': {
      id: '/_appLayout/alert'
      path: '/alert'
      fullPath: '/alert'
      preLoaderRoute: typeof AppLayoutAlertRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_appLayout/_studioLayout': {
      id: '/_appLayout/_studioLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppLayoutStudioLayoutRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_appLayout/stage/$stageId': {
      id: '/_appLayout/stage/$stageId'
      path: '/stage/$stageId'
      fullPath: '/stage/$stageId'
      preLoaderRoute: typeof AppLayoutStageStageIdRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_appLayout/_studioLayout/studio/$handle/': {
      id: '/_appLayout/_studioLayout/studio/$handle/'
      path: '/studio/$handle'
      fullPath: '/studio/$handle'
      preLoaderRoute: typeof AppLayoutStudioLayoutStudioHandleIndexRouteImport
      parentRoute: typeof AppLayoutStudioLayoutRoute
    }
    '/_appLayout/_studioLayout/studio/$handle/stages': {
      id: '/_appLayout/_studioLayout/studio/$handle/stages'
      path: '/studio/$handle/stages'
      fullPath: '/studio/$handle/stages'
      preLoaderRoute: typeof AppLayoutStudioLayoutStudioHandleStagesRouteImport
      parentRoute: typeof AppLayoutStudioLayoutRoute
    }
    '/_appLayout/_studioLayout/studio/$handle/reactions': {
      id: '/_appLayout/_studioLayout/studio/$handle/reactions'
      path: '/studio/$handle/reactions'
      fullPath: '/studio/$handle/reactions'
      preLoaderRoute: typeof AppLayoutStudioLayoutStudioHandleReactionsRouteImport
      parentRoute: typeof AppLayoutStudioLayoutRoute
    }
    '/_appLayout/_studioLayout/studio/$handle/board': {
      id: '/_appLayout/_studioLayout/studio/$handle/board'
      path: '/studio/$handle/board'
      fullPath: '/studio/$handle/board'
      preLoaderRoute: typeof AppLayoutStudioLayoutStudioHandleBoardRouteImport
      parentRoute: typeof AppLayoutStudioLayoutRoute
    }
  }
}

interface AppLayoutStudioLayoutRouteChildren {
  AppLayoutStudioLayoutStudioHandleBoardRoute: typeof AppLayoutStudioLayoutStudioHandleBoardRoute
  AppLayoutStudioLayoutStudioHandleReactionsRoute: typeof AppLayoutStudioLayoutStudioHandleReactionsRoute
  AppLayoutStudioLayoutStudioHandleStagesRoute: typeof AppLayoutStudioLayoutStudioHandleStagesRoute
  AppLayoutStudioLayoutStudioHandleIndexRoute: typeof AppLayoutStudioLayoutStudioHandleIndexRoute
}

const AppLayoutStudioLayoutRouteChildren: AppLayoutStudioLayoutRouteChildren = {
  AppLayoutStudioLayoutStudioHandleBoardRoute:
    AppLayoutStudioLayoutStudioHandleBoardRoute,
  AppLayoutStudioLayoutStudioHandleReactionsRoute:
    AppLayoutStudioLayoutStudioHandleReactionsRoute,
  AppLayoutStudioLayoutStudioHandleStagesRoute:
    AppLayoutStudioLayoutStudioHandleStagesRoute,
  AppLayoutStudioLayoutStudioHandleIndexRoute:
    AppLayoutStudioLayoutStudioHandleIndexRoute,
}

const AppLayoutStudioLayoutRouteWithChildren =
  AppLayoutStudioLayoutRoute._addFileChildren(
    AppLayoutStudioLayoutRouteChildren,
  )

interface AppLayoutRouteChildren {
  AppLayoutStudioLayoutRoute: typeof AppLayoutStudioLayoutRouteWithChildren
  AppLayoutAlertRoute: typeof AppLayoutAlertRoute
  AppLayoutSearchRoute: typeof AppLayoutSearchRoute
  AppLayoutSettingRoute: typeof AppLayoutSettingRoute
  AppLayoutIndexRoute: typeof AppLayoutIndexRoute
  AppLayoutStageStageIdRoute: typeof AppLayoutStageStageIdRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppLayoutStudioLayoutRoute: AppLayoutStudioLayoutRouteWithChildren,
  AppLayoutAlertRoute: AppLayoutAlertRoute,
  AppLayoutSearchRoute: AppLayoutSearchRoute,
  AppLayoutSettingRoute: AppLayoutSettingRoute,
  AppLayoutIndexRoute: AppLayoutIndexRoute,
  AppLayoutStageStageIdRoute: AppLayoutStageStageIdRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

interface LandingLayoutRouteChildren {
  LandingLayoutLoginRoute: typeof LandingLayoutLoginRoute
  LandingLayoutSignupRoute: typeof LandingLayoutSignupRoute
}

const LandingLayoutRouteChildren: LandingLayoutRouteChildren = {
  LandingLayoutLoginRoute: LandingLayoutLoginRoute,
  LandingLayoutSignupRoute: LandingLayoutSignupRoute,
}

const LandingLayoutRouteWithChildren = LandingLayoutRoute._addFileChildren(
  LandingLayoutRouteChildren,
)

interface StackedLayoutRouteChildren {
  StackedLayoutUploadRoute: typeof StackedLayoutUploadRoute
}

const StackedLayoutRouteChildren: StackedLayoutRouteChildren = {
  StackedLayoutUploadRoute: StackedLayoutUploadRoute,
}

const StackedLayoutRouteWithChildren = StackedLayoutRoute._addFileChildren(
  StackedLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppLayoutRoute: AppLayoutRouteWithChildren,
  LandingLayoutRoute: LandingLayoutRouteWithChildren,
  StackedLayoutRoute: StackedLayoutRouteWithChildren,
  IntroRoute: IntroRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
