/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IntroRouteImport } from './routes/intro'
import { Route as LandingLayoutRouteImport } from './routes/_landingLayout'
import { Route as AppLayoutRouteImport } from './routes/_appLayout'
import { Route as AppLayoutIndexRouteImport } from './routes/_appLayout/index'
import { Route as LandingLayoutSignupRouteImport } from './routes/_landingLayout/signup'
import { Route as LandingLayoutLoginRouteImport } from './routes/_landingLayout/login'
import { Route as AppLayoutUploadRouteImport } from './routes/_appLayout/upload'
import { Route as AppLayoutSettingRouteImport } from './routes/_appLayout/setting'
import { Route as AppLayoutSearchRouteImport } from './routes/_appLayout/search'
import { Route as AppLayoutAlertRouteImport } from './routes/_appLayout/alert'
import { Route as AppLayoutStudioLayoutRouteImport } from './routes/_appLayout/_studioLayout'
import { Route as AppLayoutStageStageIdRouteImport } from './routes/_appLayout/stage/$stageId'
import { Route as AppLayoutStudioLayoutStudioUserIdIndexRouteImport } from './routes/_appLayout/_studioLayout/studio/$userId/index'
import { Route as AppLayoutStudioLayoutStudioUserIdStagesRouteImport } from './routes/_appLayout/_studioLayout/studio/$userId/stages'
import { Route as AppLayoutStudioLayoutStudioUserIdReactionsRouteImport } from './routes/_appLayout/_studioLayout/studio/$userId/reactions'
import { Route as AppLayoutStudioLayoutStudioUserIdBoardRouteImport } from './routes/_appLayout/_studioLayout/studio/$userId/board'

const IntroRoute = IntroRouteImport.update({
  id: '/intro',
  path: '/intro',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingLayoutRoute = LandingLayoutRouteImport.update({
  id: '/_landingLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/_appLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutIndexRoute = AppLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const LandingLayoutSignupRoute = LandingLayoutSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => LandingLayoutRoute,
} as any)
const LandingLayoutLoginRoute = LandingLayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LandingLayoutRoute,
} as any)
const AppLayoutUploadRoute = AppLayoutUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutSettingRoute = AppLayoutSettingRouteImport.update({
  id: '/setting',
  path: '/setting',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutSearchRoute = AppLayoutSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutAlertRoute = AppLayoutAlertRouteImport.update({
  id: '/alert',
  path: '/alert',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutStudioLayoutRoute = AppLayoutStudioLayoutRouteImport.update({
  id: '/_studioLayout',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutStageStageIdRoute = AppLayoutStageStageIdRouteImport.update({
  id: '/stage/$stageId',
  path: '/stage/$stageId',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutStudioLayoutStudioUserIdIndexRoute =
  AppLayoutStudioLayoutStudioUserIdIndexRouteImport.update({
    id: '/studio/$userId/',
    path: '/studio/$userId/',
    getParentRoute: () => AppLayoutStudioLayoutRoute,
  } as any)
const AppLayoutStudioLayoutStudioUserIdStagesRoute =
  AppLayoutStudioLayoutStudioUserIdStagesRouteImport.update({
    id: '/studio/$userId/stages',
    path: '/studio/$userId/stages',
    getParentRoute: () => AppLayoutStudioLayoutRoute,
  } as any)
const AppLayoutStudioLayoutStudioUserIdReactionsRoute =
  AppLayoutStudioLayoutStudioUserIdReactionsRouteImport.update({
    id: '/studio/$userId/reactions',
    path: '/studio/$userId/reactions',
    getParentRoute: () => AppLayoutStudioLayoutRoute,
  } as any)
const AppLayoutStudioLayoutStudioUserIdBoardRoute =
  AppLayoutStudioLayoutStudioUserIdBoardRouteImport.update({
    id: '/studio/$userId/board',
    path: '/studio/$userId/board',
    getParentRoute: () => AppLayoutStudioLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/intro': typeof IntroRoute
  '/alert': typeof AppLayoutAlertRoute
  '/search': typeof AppLayoutSearchRoute
  '/setting': typeof AppLayoutSettingRoute
  '/upload': typeof AppLayoutUploadRoute
  '/login': typeof LandingLayoutLoginRoute
  '/signup': typeof LandingLayoutSignupRoute
  '/': typeof AppLayoutIndexRoute
  '/stage/$stageId': typeof AppLayoutStageStageIdRoute
  '/studio/$userId/board': typeof AppLayoutStudioLayoutStudioUserIdBoardRoute
  '/studio/$userId/reactions': typeof AppLayoutStudioLayoutStudioUserIdReactionsRoute
  '/studio/$userId/stages': typeof AppLayoutStudioLayoutStudioUserIdStagesRoute
  '/studio/$userId': typeof AppLayoutStudioLayoutStudioUserIdIndexRoute
}
export interface FileRoutesByTo {
  '/intro': typeof IntroRoute
  '/alert': typeof AppLayoutAlertRoute
  '/search': typeof AppLayoutSearchRoute
  '/setting': typeof AppLayoutSettingRoute
  '/upload': typeof AppLayoutUploadRoute
  '/login': typeof LandingLayoutLoginRoute
  '/signup': typeof LandingLayoutSignupRoute
  '/': typeof AppLayoutIndexRoute
  '/stage/$stageId': typeof AppLayoutStageStageIdRoute
  '/studio/$userId/board': typeof AppLayoutStudioLayoutStudioUserIdBoardRoute
  '/studio/$userId/reactions': typeof AppLayoutStudioLayoutStudioUserIdReactionsRoute
  '/studio/$userId/stages': typeof AppLayoutStudioLayoutStudioUserIdStagesRoute
  '/studio/$userId': typeof AppLayoutStudioLayoutStudioUserIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_appLayout': typeof AppLayoutRouteWithChildren
  '/_landingLayout': typeof LandingLayoutRouteWithChildren
  '/intro': typeof IntroRoute
  '/_appLayout/_studioLayout': typeof AppLayoutStudioLayoutRouteWithChildren
  '/_appLayout/alert': typeof AppLayoutAlertRoute
  '/_appLayout/search': typeof AppLayoutSearchRoute
  '/_appLayout/setting': typeof AppLayoutSettingRoute
  '/_appLayout/upload': typeof AppLayoutUploadRoute
  '/_landingLayout/login': typeof LandingLayoutLoginRoute
  '/_landingLayout/signup': typeof LandingLayoutSignupRoute
  '/_appLayout/': typeof AppLayoutIndexRoute
  '/_appLayout/stage/$stageId': typeof AppLayoutStageStageIdRoute
  '/_appLayout/_studioLayout/studio/$userId/board': typeof AppLayoutStudioLayoutStudioUserIdBoardRoute
  '/_appLayout/_studioLayout/studio/$userId/reactions': typeof AppLayoutStudioLayoutStudioUserIdReactionsRoute
  '/_appLayout/_studioLayout/studio/$userId/stages': typeof AppLayoutStudioLayoutStudioUserIdStagesRoute
  '/_appLayout/_studioLayout/studio/$userId/': typeof AppLayoutStudioLayoutStudioUserIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/intro'
    | '/alert'
    | '/search'
    | '/setting'
    | '/upload'
    | '/login'
    | '/signup'
    | '/'
    | '/stage/$stageId'
    | '/studio/$userId/board'
    | '/studio/$userId/reactions'
    | '/studio/$userId/stages'
    | '/studio/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/intro'
    | '/alert'
    | '/search'
    | '/setting'
    | '/upload'
    | '/login'
    | '/signup'
    | '/'
    | '/stage/$stageId'
    | '/studio/$userId/board'
    | '/studio/$userId/reactions'
    | '/studio/$userId/stages'
    | '/studio/$userId'
  id:
    | '__root__'
    | '/_appLayout'
    | '/_landingLayout'
    | '/intro'
    | '/_appLayout/_studioLayout'
    | '/_appLayout/alert'
    | '/_appLayout/search'
    | '/_appLayout/setting'
    | '/_appLayout/upload'
    | '/_landingLayout/login'
    | '/_landingLayout/signup'
    | '/_appLayout/'
    | '/_appLayout/stage/$stageId'
    | '/_appLayout/_studioLayout/studio/$userId/board'
    | '/_appLayout/_studioLayout/studio/$userId/reactions'
    | '/_appLayout/_studioLayout/studio/$userId/stages'
    | '/_appLayout/_studioLayout/studio/$userId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
  LandingLayoutRoute: typeof LandingLayoutRouteWithChildren
  IntroRoute: typeof IntroRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/intro': {
      id: '/intro'
      path: '/intro'
      fullPath: '/intro'
      preLoaderRoute: typeof IntroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landingLayout': {
      id: '/_landingLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LandingLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_appLayout': {
      id: '/_appLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_appLayout/': {
      id: '/_appLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppLayoutIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_landingLayout/signup': {
      id: '/_landingLayout/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof LandingLayoutSignupRouteImport
      parentRoute: typeof LandingLayoutRoute
    }
    '/_landingLayout/login': {
      id: '/_landingLayout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LandingLayoutLoginRouteImport
      parentRoute: typeof LandingLayoutRoute
    }
    '/_appLayout/upload': {
      id: '/_appLayout/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AppLayoutUploadRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_appLayout/setting': {
      id: '/_appLayout/setting'
      path: '/setting'
      fullPath: '/setting'
      preLoaderRoute: typeof AppLayoutSettingRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_appLayout/search': {
      id: '/_appLayout/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppLayoutSearchRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_appLayout/alert': {
      id: '/_appLayout/alert'
      path: '/alert'
      fullPath: '/alert'
      preLoaderRoute: typeof AppLayoutAlertRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_appLayout/_studioLayout': {
      id: '/_appLayout/_studioLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppLayoutStudioLayoutRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_appLayout/stage/$stageId': {
      id: '/_appLayout/stage/$stageId'
      path: '/stage/$stageId'
      fullPath: '/stage/$stageId'
      preLoaderRoute: typeof AppLayoutStageStageIdRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_appLayout/_studioLayout/studio/$userId/': {
      id: '/_appLayout/_studioLayout/studio/$userId/'
      path: '/studio/$userId'
      fullPath: '/studio/$userId'
      preLoaderRoute: typeof AppLayoutStudioLayoutStudioUserIdIndexRouteImport
      parentRoute: typeof AppLayoutStudioLayoutRoute
    }
    '/_appLayout/_studioLayout/studio/$userId/stages': {
      id: '/_appLayout/_studioLayout/studio/$userId/stages'
      path: '/studio/$userId/stages'
      fullPath: '/studio/$userId/stages'
      preLoaderRoute: typeof AppLayoutStudioLayoutStudioUserIdStagesRouteImport
      parentRoute: typeof AppLayoutStudioLayoutRoute
    }
    '/_appLayout/_studioLayout/studio/$userId/reactions': {
      id: '/_appLayout/_studioLayout/studio/$userId/reactions'
      path: '/studio/$userId/reactions'
      fullPath: '/studio/$userId/reactions'
      preLoaderRoute: typeof AppLayoutStudioLayoutStudioUserIdReactionsRouteImport
      parentRoute: typeof AppLayoutStudioLayoutRoute
    }
    '/_appLayout/_studioLayout/studio/$userId/board': {
      id: '/_appLayout/_studioLayout/studio/$userId/board'
      path: '/studio/$userId/board'
      fullPath: '/studio/$userId/board'
      preLoaderRoute: typeof AppLayoutStudioLayoutStudioUserIdBoardRouteImport
      parentRoute: typeof AppLayoutStudioLayoutRoute
    }
  }
}

interface AppLayoutStudioLayoutRouteChildren {
  AppLayoutStudioLayoutStudioUserIdBoardRoute: typeof AppLayoutStudioLayoutStudioUserIdBoardRoute
  AppLayoutStudioLayoutStudioUserIdReactionsRoute: typeof AppLayoutStudioLayoutStudioUserIdReactionsRoute
  AppLayoutStudioLayoutStudioUserIdStagesRoute: typeof AppLayoutStudioLayoutStudioUserIdStagesRoute
  AppLayoutStudioLayoutStudioUserIdIndexRoute: typeof AppLayoutStudioLayoutStudioUserIdIndexRoute
}

const AppLayoutStudioLayoutRouteChildren: AppLayoutStudioLayoutRouteChildren = {
  AppLayoutStudioLayoutStudioUserIdBoardRoute:
    AppLayoutStudioLayoutStudioUserIdBoardRoute,
  AppLayoutStudioLayoutStudioUserIdReactionsRoute:
    AppLayoutStudioLayoutStudioUserIdReactionsRoute,
  AppLayoutStudioLayoutStudioUserIdStagesRoute:
    AppLayoutStudioLayoutStudioUserIdStagesRoute,
  AppLayoutStudioLayoutStudioUserIdIndexRoute:
    AppLayoutStudioLayoutStudioUserIdIndexRoute,
}

const AppLayoutStudioLayoutRouteWithChildren =
  AppLayoutStudioLayoutRoute._addFileChildren(
    AppLayoutStudioLayoutRouteChildren,
  )

interface AppLayoutRouteChildren {
  AppLayoutStudioLayoutRoute: typeof AppLayoutStudioLayoutRouteWithChildren
  AppLayoutAlertRoute: typeof AppLayoutAlertRoute
  AppLayoutSearchRoute: typeof AppLayoutSearchRoute
  AppLayoutSettingRoute: typeof AppLayoutSettingRoute
  AppLayoutUploadRoute: typeof AppLayoutUploadRoute
  AppLayoutIndexRoute: typeof AppLayoutIndexRoute
  AppLayoutStageStageIdRoute: typeof AppLayoutStageStageIdRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppLayoutStudioLayoutRoute: AppLayoutStudioLayoutRouteWithChildren,
  AppLayoutAlertRoute: AppLayoutAlertRoute,
  AppLayoutSearchRoute: AppLayoutSearchRoute,
  AppLayoutSettingRoute: AppLayoutSettingRoute,
  AppLayoutUploadRoute: AppLayoutUploadRoute,
  AppLayoutIndexRoute: AppLayoutIndexRoute,
  AppLayoutStageStageIdRoute: AppLayoutStageStageIdRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

interface LandingLayoutRouteChildren {
  LandingLayoutLoginRoute: typeof LandingLayoutLoginRoute
  LandingLayoutSignupRoute: typeof LandingLayoutSignupRoute
}

const LandingLayoutRouteChildren: LandingLayoutRouteChildren = {
  LandingLayoutLoginRoute: LandingLayoutLoginRoute,
  LandingLayoutSignupRoute: LandingLayoutSignupRoute,
}

const LandingLayoutRouteWithChildren = LandingLayoutRoute._addFileChildren(
  LandingLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppLayoutRoute: AppLayoutRouteWithChildren,
  LandingLayoutRoute: LandingLayoutRouteWithChildren,
  IntroRoute: IntroRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
