/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as SettingRouteImport } from './routes/setting'
import { Route as SearchRouteImport } from './routes/search'
import { Route as AlertRouteImport } from './routes/alert'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StageStageIdRouteImport } from './routes/stage/$stageId'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingRoute = SettingRouteImport.update({
  id: '/setting',
  path: '/setting',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertRoute = AlertRouteImport.update({
  id: '/alert',
  path: '/alert',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StageStageIdRoute = StageStageIdRouteImport.update({
  id: '/stage/$stageId',
  path: '/stage/$stageId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alert': typeof AlertRoute
  '/search': typeof SearchRoute
  '/setting': typeof SettingRoute
  '/studio': typeof StudioRoute
  '/upload': typeof UploadRoute
  '/stage/$stageId': typeof StageStageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alert': typeof AlertRoute
  '/search': typeof SearchRoute
  '/setting': typeof SettingRoute
  '/studio': typeof StudioRoute
  '/upload': typeof UploadRoute
  '/stage/$stageId': typeof StageStageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alert': typeof AlertRoute
  '/search': typeof SearchRoute
  '/setting': typeof SettingRoute
  '/studio': typeof StudioRoute
  '/upload': typeof UploadRoute
  '/stage/$stageId': typeof StageStageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alert'
    | '/search'
    | '/setting'
    | '/studio'
    | '/upload'
    | '/stage/$stageId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alert'
    | '/search'
    | '/setting'
    | '/studio'
    | '/upload'
    | '/stage/$stageId'
  id:
    | '__root__'
    | '/'
    | '/alert'
    | '/search'
    | '/setting'
    | '/studio'
    | '/upload'
    | '/stage/$stageId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertRoute: typeof AlertRoute
  SearchRoute: typeof SearchRoute
  SettingRoute: typeof SettingRoute
  StudioRoute: typeof StudioRoute
  UploadRoute: typeof UploadRoute
  StageStageIdRoute: typeof StageStageIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setting': {
      id: '/setting'
      path: '/setting'
      fullPath: '/setting'
      preLoaderRoute: typeof SettingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alert': {
      id: '/alert'
      path: '/alert'
      fullPath: '/alert'
      preLoaderRoute: typeof AlertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stage/$stageId': {
      id: '/stage/$stageId'
      path: '/stage/$stageId'
      fullPath: '/stage/$stageId'
      preLoaderRoute: typeof StageStageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertRoute: AlertRoute,
  SearchRoute: SearchRoute,
  SettingRoute: SettingRoute,
  StudioRoute: StudioRoute,
  UploadRoute: UploadRoute,
  StageStageIdRoute: StageStageIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
